### ISSUE TITLE
VIP1: Reworking functionality.yaml

### ISSUE THREAD

**Issue by rcannood** [viash-io/viash#1]
**Viash Improvement Protocol 1**

Some naming conventions in the functionality.yaml are, by now, somewhat illogical. 

* Issue A: resources typically have the same name as their path, so that could be dropped by default
* Issue B: The `platform` variable is confusing with respect to the platform yaml. I would make this a variable in each of the resources instead, see example below.
* Issue C: `ftype` should be renamed to `function_type` since no other names are abbreviated.
* Issue D: I would like to define more default values. These changes will be reflected in the Scala code as well.

<details><summary>Example of current functionality.yaml</summary>

```yaml
name: starReport
description: Generate STAR Report
platform: bash
ftype: convert
arguments:
- name: "--workDir"
  type: file
  required: true
  default: /tmp/STARR
  direction: input
- name: "--logFile"
  type: string
  required: true
  default: output.log
  direction: output
resources:
- name: main
  path: ./code.sh
- name: STARR.R
  path: ./STARR.R
- name: 01_featureAnnotation.R
  path: ./01_featureAnnotation.R
- name: 02_eSet.R
  path: ./02_eSet.R
```

</details>

<details><summary>Proposed format</summary>

```yaml
name: starReport
description: Generate STAR Report
function_type: convert             # C) rename
arguments:
- name: "--workDir"
  type: file
  required: true
  default: /tmp/STARR
  direction: input                 # D) default, so can be dropped
- name: "--logFile"
  type: string                     # D) default??
  required: false                  # D) required: false is default
  default: output.log
  direction: output
files:
- type: bash_script                # B) change 'platform' so it is tightly coupled with the file it affects
  path: ./code.sh         
- type: resource                   # B) resource is the default type so can be omitted
  path: ./STARR.R
- path: ./01_featureAnnotation.R   # A) by default, the same name as specified in the path will be used
- name: foo.R                      # A) but this can be overridden
  path: ./02_eSet.R
- name: myfile.txt
  content: custom content          # B) you can still create files inside the yaml
```

</details>

Checklist:
* [x] @rcannood: Any additional proposals?
* [x] @tverbeiren : Any additional proposals?
* [x] @rcannood: Agree to accept VIP1
* [x] @tverbeiren : Agree to accept VIP1

If this VIP is accepted, update the following files
* [x] scala code in Viash source code
* [x] functionality yamls at [Viash/atoms](https://github.com/data-intuitive/Viash/tree/master/atoms)
* [x] functionality yamls at [Viash/src/test/resources](https://github.com/data-intuitive/Viash/tree/master/src/test/resources)
* [x] functionality yamls at [pipeline_sarscov2/functionality](https://github.com/data-intuitive/pipeline_sarscov2/tree/master/functionality)
