### ISSUE TITLE
Volumes are not mounting correctly when running Docker in Docker using docker.sock

### ISSUE THREAD

**Issue by BlackDragonBE** [viash-io/viash#109]
### Situation

I have Viash component A that uses a Docker platform with `run_args: ["--volume /var/run/docker.sock:/var/run/docker.sock"]` to pass the host's Docker socket. This way, Docker on the host can be called via Docker CLI in the container. This container (let's call it container A) builds and starts another container:

Host with Docker installed
└─starts─ Docker container A built by Viash which uses docker cli and docker.sock of host
    └─starts─ Docker container B built by Viash
 
Container A has a component that references a folder from the host:

```
  arguments:
    - name: "folder"
      type: file
      description: A folder
      default: "."
```

Container B has a component that needs to read a file:

```
  arguments:
  - name: input                           
    type: file
    description: The input file.
```

The input path passed to the component points to a file in container A.
While trying to run this component though, it can't find the file that was passed as an argument as the files of the host aren't passed to Container B.

### Solution

A possible solution to this issue is detecting when a container is called from within another container and passing paths relative to the docker host instead of the container it's running in: https://forums.docker.com/t/mounting-a-volume-not-working-with-running-docker-in-docker/25775/3
