### ISSUE TITLE
Encode/Decode infinite / missing values

### ISSUE THREAD

**Issue by rcannood** [viash-io/viash#110]
Related to commit c2ec4aa. Viash should be able to accept infinite integer/double values and translate this correctly into downstream parameter blocks.

For instance:

```yaml
- name: foo
  type: integer
  default: posinf
```

or 
```sh
my_component --foo "neginf"
