### ISSUE TITLE
Ability to define subcommands with Viash

### ISSUE THREAD

**Issue by tverbeiren** [viash-io/viash#125]
It would be nice if Viash could support subcommands like used with `git`, `docker`, `aws-cli`, ... and Viash itself.

Maybe an extra layer in `arguments` could be introduced?

```yaml
functionality:
  arguments:
    help
      - type: string
        name: "--help"
     build
       - type: file
         name: config
         default: config.vsh.yaml
         required: true
       ...
  ...
```

We do have `inputs` and `outputs` already at this level, so we may have to be smarter about it.

As a first use case, we could create a Viash component for a simplified `git` client running in a container or something?
