### ISSUE TITLE
Ability for argument validation

### ISSUE THREAD

**Issue by tverbeiren** [viash-io/viash#126]
Viash supports validating argument types, but it would be nice to be able to specify possible argument values from a list or using a regex.

```
arguments:
  - name: "mode"
    type: string
    match_list: [ "help", "pull", "push" ]
...
```

or

```
arguments:
  - name: "hidden_file_input"
    type: file
    match_regex: '^\.'
...
```
