### ISSUE TITLE
`bc` has become a dependency for docker containers when using `viash test -p docker`

### ISSUE THREAD

**Issue by DriesSchaumont** [viash-io/viash#150]
When creating a component with an argument that has a `min` property and `docker` as platform, running `viash test -p docker` fails when there is no `bc` installed in the container. 

```bash
./foo: bc: command not found
```

This problem occurs because when using viash test, a native executable is created within the docker contanier for that unittest. This executable is then executed within the container, envoking the command line arguments parsing, and triggering the need for `bc`. Please find an example below (note that the python:3.9-buster containers do not contain `bc`).  

`foo.vsh.yaml`
```yaml
functionality:
  name: foo
  arguments:
    - name: "--input"
      alternatives: ["-i"]
      type: integer
      min: 1
      default: 1
    - name: "--output"
      type: file
      alternatives: ["-o"]
  resources:
    - type: python_script
      path: ./script.py
  test_resources:
    - type: python_script
      path: test.py
platforms:
  - type: docker
    image: python:3.9-buster
```

`script.py`
```python3
if __name__ == "__main__":
    with open(par["output"], 'w')  as open_file:
         open_file.write(int(par["input"])**2)
```

`test.py`
```python3
import subprocess
from pathlib import Path

out = subprocess.check_output([
      "./" + meta["functionality_name"],
      "--input", "1" 
      "--output", "test_output"
    ]).decode("utf-8")
self.assertTrue(Path("test_output").is_file())
```

**Comment by Grifs** [comment]
BashWrapper now displays a warning and skips the checks.
To be extended later to use fallbacks with e.g.:
- awk
- Python
- R
- ...

**Comment by Grifs** [comment]
note to self (or others that may work on this in the future), I was using this config as basis to test the new checks:

```yaml
functionality:
  name: foo
  arguments:
    - name: "--input"
      alternatives: ["-i"]
      type: integer
      min: 1
      default: 1
    - name: "--input2"
      type: double
      min: 1.1
  resources:
    - type: python_script
      text: |
        print("input: " + str(par["input"]))
        print("input2: " + str(par["input2"]))
  test_resources:
    - type: python_script
      text: |
        import subprocess
        out = subprocess.check_output([
          "./" + meta["functionality_name"],
          "--input", "1",
          "--input2", "1.1",
          ]).decode("utf-8")
        print(out)
platforms:
  - type: docker
    image: python:3.9-buster
```
