### ISSUE TITLE
Add argument groups

### ISSUE THREAD

**Issue by Grifs** [viash-io/viash#154]
In the functionality config, add option to group arguments into groups.

Advantage could be to organize the help output into sections

**Comment by rcannood** [comment]
Option 1:
```
arguments:
  - name: "--input"
    type: file
    group: io
  - name: "--output"
    type: file
    direction: output
    group: io
```

Option 2:

```
arguments:
  - name: "--input"
    type: file
  - name: "--output"
    type: file
    direction: output
argument_groups:
  io: [ input, output ]
```

**Comment by rcannood** [comment]
Update: we went with option 3.


Option 3:

```
arguments:
  - name: "--input"
    type: file
  - name: "--output"
    type: file
    direction: output
argument_groups:
  - name: Input/Output
    description: Foo Bar Baz         # optional
    arguments: [input, output]
```


Defining argument groups would (amongst others) result in a grouped help message:

```
mytool

mytool description

Arguments:
    --foo
        type: file, output
        example: output.txt
        Path to the output.

<group_name> arguments:
    <group_description>

    --input
        type: file
        example: input.txt
        Path to the sample.

    --output
        type: file, output
        example: output.txt
        Path to the output.
