### ISSUE TITLE
NXF image points to autogenerated docker image name in case no modifications are applied

### ISSUE THREAD

**Issue by tverbeiren** [viash-io/viash#16]
Given:

```
platforms:
  - type: docker
    image: dpokidov/imagemagick
  - type: nextflow
```

The NextFlow image name will point to an autogenerated image name for the component, not the Docker hub image. This leads to errors.

Temporary workaround is simply:

```
platforms:
  - type: docker
    image: dpokidov/imagemagick
  - type: nextflow
    image: dpokidov/imagemagick
```
