### ISSUE TITLE
Add organisation to the config spec

### ISSUE THREAD

**Issue by tverbeiren** [viash-io/viash#165]
Viash would benefit from being able to store an _organisation_ attribute next to _namespace_ and _name_.

The role of this attribute and the relation to the organisation in the Docker platform should be made clear.

**Comment by rcannood** [comment]
Let's add this to the functionality:

```yaml
functionality:
  name: foo
  namespace: bar
  organization: thisisme
```

We should be able to set the organization in the project config file, e.g.:

Contents of `_viash.yaml`:
```yaml
functionality:
  organization: thisisme
```

(Related to #300)
