### ISSUE TITLE
refactor argument groups

### ISSUE THREAD

**Issue by rcannood** [viash-io/viash#186]
Argument groups are useful for grouping arguments in components with a lot of components, e.g. https://github.com/czbiohub/mspipelines/blob/83e7ed438679c2970cc37186fe67d6f8021d8b3d/src/msdial/msdial_lcms/config.vsh.yaml .

However the notation gets tedious, because you need to copy paste around all of the argument names. 

Proposal : change the arggroup.arguments from List[String] into List[Argument[_]] and just specify the arguments directly in the group.

I'm also thinking that inputs and outputs as separate fields may not have been a good idea, especially now that we have arg groups.

**Comment by rcannood** [comment]
Example of the current format:
```yaml
arguments:
  - { name: "--one", type: string }
  - { name: "--two", type: string }
  - { name: "--three", type: string }
  - { name: "--four", type: string }
argument_groups:
  - name: Even
    arguments: [ two, four ]
  - name: Uneven
    arguments: [ one, three ]
```

Proposed format:
```yaml
arguments:
  - name: Even
    arguments:
    - { name: "--two", type: string }
    - { name: "--four", type: string }
  - name: Uneven
    arguments:
    - { name: "--one", type: string }
    - { name: "--three", type: string }
```
