### ISSUE TITLE
Check is all requirements are met for a docker image to be fully compatible with nextflow.

### ISSUE THREAD

**Issue by DriesSchaumont** [viash-io/viash#187]
When a component is defined to use a docker container, executing that container with `nextflow run` causes errors when the option `-with-trace` is provided and the container does not provide `ps`

For example:

Using the following `config.vsh.yaml`:

```yaml
functionality:
  name: myscript
  arguments:
    - name: "--output"
      required: true
      type: file
  resources:
    - type: python_script
      path: script.py
      text: |
        with open(par['output'], 'w') as open_f:
            open_f.write('This is a test')
platforms:
    - type: docker
      image: python:3.8-slim
    - type: nextflow
      variant: vdsl3
```

And build commands:

```bash
viash build config.vsh.yaml -p nextflow -o ./output/component/ --write_meta
viash build config.vsh.yaml -p docker -o ./output/docker/ --write_meta --setup alwaysbuild
```

With a `nextflow.config`: 
```
profiles  {
  docker {
    docker.enabled         = true
    docker.userEmulation   = true
    singularity.enabled    = false
    podman.enabled         = false
    shifter.enabled        = false
    charliecloud.enabled   = false
  }
}
```

and the following `run` command:

```
nextflow run . -main-script output/component/main.nf --output "test.txt" --publish_dir foo/ -with-trace work/trace.txt -profile docker
```

Results in:

```
Command 'ps' required by nextflow to collect task metrics cannot be found
```

It would be ideal if Viash could output a warning when building a container for a nextflow target and that container does not provide `ps` or other dependencies: https://www.nextflow.io/docs/latest/tracing.html#tasks
