### ISSUE TITLE
Allow setting the number of processes and memory limit

### ISSUE THREAD

**Issue by rcannood** [viash-io/viash#194]
In some components (e.g. cellranger), the tool needs to know the number of processes or memory available. Up until now, we solved this by having explicit memory/cores arguments:

```yaml
functionality:
  name: foo
  arguments:
    # runtime args
    - type: integer
      name: --cores
      description:  Set max cores the pipeline may request at one time.
      example: 2
    - type: integer
      name: --memory
      description: Set max GB the pipeline may request at one time.
      example: 10
```

It'd be a better idea to support this in Viash natively by having the executable/module define values for in `meta`:
  * `meta["n_proc"]`: Number of processes the application is allowed to spawn at most
  * `meta["memory_b"]`: Max memory usage in bytes
  * `meta["memory_kb"]`: Max memory usage in KB
  * `meta["memory_mb"]`: Max memory usage in MB
  * `meta["memory_gb"]`: Max memory usage in GB
  * `meta["memory_tb"]`: Max memory usage in TB
  * ...

---

Question 1: When no n_proc is provided by the user, what should be the default value for `meta["n_proc"]`? Possibilities:
  * ✓ `meta["n_proc"]` is unset. Trying to access this field throws an error.
  * `meta["n_proc"]` is set to `0`.
  * `meta["n_proc"]` is set to 90% of available threads on this system. This will require some fancy arithmetic.
---

Question 2: When the user specifies 500MB, what should `meta["memory_gb"]` be set to?
  * `meta["memory_gb"]` is unset.
  * Round down: `0`.
  * ✓ Round up: `1`.
  * Round to nearest, unless that ends up being 0.
  * Return as a float: `0.5`.

Answer: 
```bash
memory_b=1099511627776
memory_kb=$(( ($memory_b+1023) / 1024 ))
memory_mb=$(( ($memory_kb+1023) / 1024 ))
memory_gb=$(( ($memory_mb+1023) / 1024 ))
memory_tb=$(( ($memory_gb+1023) / 1024 ))
memory_pb=$(( ($memory_tb+1023) / 1024 ))

echo "memory b: $memory_b"
echo "memory kb: $memory_kb"
echo "memory mb: $memory_mb"
echo "memory gb: $memory_gb"
echo "memory tb: $memory_tb"
echo "memory pb: $memory_pb"
```
---
Q3: Where to fill in default values for n_proc and memory?

* ✓ In `.functionality.requirements`:
  ```yaml
  functionality:
    name: foo
    requirements:
      n_proc: 10
      memory: 10G
  ```
* In `.global`:
  ```yaml
  functionality:
    name: foo
  global:
    n_proc: 10
    memory: 10G
  ```
* In `.functionality.resources`:
  ```yaml
  functionality:
    name: foo
    resources:
      - type: r_script
        path: foo.R
      - type: specs
        n_proc: 10
        memory: 10G
  ```
* In each of the platforms:
  ```yaml
  functionality:
    name: foo
  platforms:
    - type: native
      n_proc: 10
      memory: 10G
    - type: docker
      image: foo
      n_proc: 10
      memory: 10G
    - type: nextflow
      directives:
        n_proc: 10
        memory: 10G
  ```
* Allow defining the requirement in both places, values get merged
  ```yaml
  functionality:
    name: foo
    requirements:
      n_proc: 10
      memory: 10G
  platforms:
    - type: native
    - type: docker
      image: foo
      requirements:
        n_proc: 15
    - type: nextflow
      requirements:
        n_proc: 20
        memory: 20G
  ```
  Translates into:
    - native: nproc 10, memory 10G
    - docker: nproc 15, memory 10G
    - nextflow: nproc 20, memory 20G

---
Q4: What to call the number of processes a job is allowed to spawn? Example, a computer might have 2 CPUs, with 8 cores and 16 threads per CPU. The total number of available threads is 32.

* ✓ `meta["n_proc"]`
* `meta["n_processes"]`
* `meta["n_cpus"]`
* `meta["n_threads"]`
* `meta["n_cores"]`

---
Q5: Do we allow the user to only specify the max memory and max processes (and call this `memory` and `n_proc`)? Or do we also allow setting the minimum requirements?

* ✓ Define only `meta["n_proc"]` and `meta["memory_..."]` and is set by:
  ```yaml
  functionality:
    name: foo
    requirements:
      n_proc: 10
      memory: 10G
  ```
* Define `meta["min_proc"]`, `meta["max_proc"]`,  `meta["min_memory_..."]`  and `meta["max_memory_..."]`,  and is set by:
  ```yaml
  functionality:
    name: foo
    requirements:
      min_proc: 1
      max_proc: 10
      min_memory: 1G
      max_memory: 10G
  ```

---
Q6: Should the executable parameters have double or triple dashes `--n_proc` or `---n_proc`? Having double dashes introduces a reserved keyword for the end users but might be less confusing.

---

In the context of a native platform:
 * By default, memory is unset
 * By default, n_proc is unset
 * User can override the default setting by:
   ```yaml
   platforms:
     - type: native
       n_proc: 10
       memory: 10GB
   ```
 * User can override this at runtime by calling `./foo ---n_proc 5 ---mem 4G`.
   The `---memory` argument can accept values such as `---memory 1000` (in bytes), `---memory 10g`, `---memory 3T`, `---memory 3kb`.
 * Effect: 
   - If not enough cores are available, the script throws an error.
   - If not enough memory is available, the script throws an error.
   - `meta["n_proc"]` and `meta["memory_..."]` and other versions are defined.

---

In the context of a Docker platform:
 * By default, memory is unset (see Q1)
 * By default, n_proc is unset (see Q1)
 * User can override the default setting by:
   ```yaml
   platforms:
     - type: docker
       n_proc: 10
       memory: 10G
   ```
 * User can override this at runtime by calling `./foo ---n_proc 5 ---memory 4`.
   The `---memory` argument can accept values such as `---memory 1000` (in bytes), `---memory 10g`, `---memory 3T`, `---memory 3kb`.
 * Effects: 
   - If not enough cores are available, the script throws an error.
   - If not enough memory is available, the script throws an error.
   - `meta["n_proc"]` and `meta["memory_..."]` and other versions are defined.
   - Values are passed to `docker run` using the `--memory` and `--cpus` parameters.

---

In the context of a Nextflow platform:
 * Number of processes or memory can be defined using the `cpus` and `memory` directives.
 * Users can define defaults as follows:
   ```yaml
   platforms:
     - type: nextflow
       directives:
         cpus: 10
         memory: 10G
   ```
 * User can override this at runtime by creating a file `nextflow.config`:
   ```groovy
   process.memory = '10G'
   process.cpus = 4
   ```
   This config then has to be passed to `nextflow run` with `-c nextflow.config`.
 * Effects: 
   - If not enough cores are available, Nextflow throws an error.
   - If not enough memory is available, Nextflow throws an error.
   - `meta["n_proc"]` and `meta["memory_..."]` and other versions are defined.
