### ISSUE TITLE
Split up platforms into targets and containers

### ISSUE THREAD

**Issue by rcannood** [viash-io/viash#195]
```yaml
functionality:
  name: foo
  requirements:
    n_proc: 10
    memory: 10G
    commands: [ sed ]
targets/artifacts/runners/executors/...:
  - type: executable
    default_backend: native
  - type: nextflow
    directives: foo
  - type: snakemake
backend/containers/images/environments/...:
  - type: docker
    image: foo
    setup: 
      - type: r
        packages: tidyverse
 - type: conda
   ...
```

What to call the targets and runtime environments, though?

* Targets / artifacts / runners / executors / ... ?
* Environments / Runtime environments / Compute environments / runners / backends / deployment / infrastructure
