### ISSUE TITLE
When a git commit is not (yet) available, Viash creates a faulty `Dockerfile`

### ISSUE THREAD

**Issue by tverbeiren** [viash-io/viash#210]
When no initial git commit is made yet, the following config just based on a base image:

```yaml
...
platforms:
  - type: docker
    image: ubuntu:20.04
```

Generates a `Dockerfile` like this:

```
...
LABEL org.opencontainers.image.revision="HEAD
fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'"
...
```
