### ISSUE TITLE
Container port should be allowed to be of 'number' type

### ISSUE THREAD

**Issue by tverbeiren** [viash-io/viash#225]
In the Viash spec, under `platforms`, `type: docker` there is an option to provide a port 'number' or a list of port 'numbers. The problem is that Viash expects to find strings there:

```yaml
platforms:
  - type: docker
     port: [ "8888" ]
```

This works, but the following does not:

```yaml
  - type: docker
    port: [ 8888 ]
```

This should clearly work as well.
