### ISSUE TITLE
Allow zero arguments

### ISSUE THREAD

**Issue by rcannood** [viash-io/viash#23]
The following yaml:
```yaml
functionality:
  name: test
  resources:
    - type: bash_script
      dest: script.sh
      text: |
        echo Hello world
platforms:
  - type: native
```

Produces an error:
```bash
$ viash run config.vsh.yaml 
Exception in thread "main" DecodingFailure(Attempt to decode value on failed cursor, List(DownField(arguments), DownField(functionality)))
```

This problem can be avoided by specifying arguments as an empty list:
```yaml
functionality:
  name: test
  resources:
    - type: bash_script
      dest: script.sh
      text: |
        echo Hello world
  arguments: []
platforms:
  - type: native
```

However, viash should be changed such that the first yaml also works.
