### ISSUE TITLE
Check multiplicity of arguments in the same argument group

### ISSUE THREAD

**Issue by rcannood** [viash-io/viash#233]
It'd be great to have a way for specifying that all arguments in the same argument group must have the same multiplicity. Example:

```yaml
    - name: Sample sheet
      arguments:
        - type: string
          name: --id
          required: true
          multiple: true
        - type: string
          name: --foo
          required: false
          multiple: true
        - type: string
          name: --bar
          required: false
          multiple: true
        - type: double
          name: --baz
          required: false
          multiple: true
      multiplicity: same
```

* Specifying `multiplicity: same` would check whether the length of all defined arguments are the same. 
* Specifying `multiplicity: same_or_one` would check whether the length of all defined arguments are the same or is equal to 1.

This functionality would works together well in combination with VDSL3, which can ingest YAML or CSV tables in order to populate the arguments.
