### ISSUE TITLE
Remove duplicate auto-detected mounts

### ISSUE THREAD

**Issue by rcannood** [viash-io/viash#257]
Viash executable pass duplicate mounts to Docker. For example, with the following component:

```yaml
functionality:
  name: foo
  arguments:
    - name: "--input"
      type: file
      multiple: true
  resources:
    - type: python_script
      path: script.py
      text: print(par)
platforms:
  - type: docker
    image: python:3.10
```

Running `bin/foo --input one --input one` will cause the generated docker command to be:

```bash
docker run --entrypoint=bash -i --rm \
  -v "/foo/test:/viash_automount/foo/test" \
  -v "/foo/test:/viash_automount/foo/test" \
  -v "/foo/test/bin:/viash_automount/foo/test/bin" \
  -v "/foo/test/bin:/viash_automount/foo/test/bin" \
  -v "/foo/workspace/viash_temp:/viash_automount/foo/workspace/viash_temp" \
  foo:latest
```

Duplicate mounts (even if they are exactly the same) will result in an error being thrown by podman.
