### ISSUE TITLE
relative paths does not work when `type: executable`

### ISSUE THREAD

**Issue by rcannood** [viash-io/viash#26]
```yaml
functionality:
  name: test
  arguments:
    - name: "path"
      type: file
      default: .
  resources:
    - type: executable
      path: ls
platforms:
  - type: docker
    image: alpine:latest
```

Running `viash run src/config.vsh.yaml -- src` should list the directories in the home directory, but it doesn't do it in time.

This is because the generated bash code is in the wrong order:
```sh
if [ ! -z "$VIASH_PAR_PATH" ]; then
  VIASH_EXECUTABLE_ARGS="$VIASH_EXECUTABLE_ARGS '$VIASH_PAR_PATH'"
fi

# detect volumes from file arguments
if [ ! -z "$VIASH_PAR_PATH" ]; then
  VIASH_EXTRA_MOUNTS="$VIASH_EXTRA_MOUNTS $(ViashAutodetectMountArg "$VIASH_PAR_PATH")"
  VIASH_PAR_PATH=$(ViashAutodetectMount "$VIASH_PAR_PATH")
fi

eval docker run --entrypoint='' -i --rm $VIASH_EXTRA_MOUNTS alpine:latest ls $VIASH_EXECUTABLE_ARGS
```
