### ISSUE TITLE
Create `target` structure for `docker_platform`

### ISSUE THREAD

**Issue by Grifs** [viash-io/viash#263]
The `target_*` fields in `docker_platform` would be better if there were restructured into a structure:

from
```
target_registry: foo
target_image: ghcr.io
target_organization: viash-io
target_tag: 0.1.0
```

to
```
target:
  registry: ghcr.io
  organisation: viash-io
  image: foo
  tag: 0.1.0
```

Neither of these are recommended to fill in manually, because
* tag: automatically filled in with `functionality.version`
* image: automatilly filled in with `${functionality.namespace}/${functionality/name}`
* organization and registry: should be defined globally by `--registry` and `--organization` arguments when running `viash_install`
* Additionally target_image_source: this too is set by `viash_install`
