### ISSUE TITLE
Fixing the resource paths when inheriting from (multiple) yamls

### ISSUE THREAD

**Issue by rcannood** [viash-io/viash#272]
I'm going to pass on fixing the resource paths when inheriting from (multiple) yamls (see #271)

Example:

Contents of `src/foo/config.vsh.yaml`:
```yaml
__inherits__: [ ../bar/resource1.yaml , ../zap/resource2.yaml ]
functionality:
  name: test
  resources:
    - type: bash_script
      path: script.sh
```

Contents of `src/bar/resource1.yaml`:
```yaml
functionality:
  test_resources:
    - type: file
      path: bar
```

Contents of `src/zap/resource2.yaml`:
```yaml
functionality:
  test_resources:
    - type: file
      path: zap
```

Should `bar` refer to `src/bar/bar` or `src/foo/bar`? At the moment, `bar` will resolve to `src/foo/bar`, but it should actually resolve to `src/bar/bar`.

_Originally posted by @rcannood in https://github.com/viash-io/viash/issues/271#issuecomment-1291425397_
