### ISSUE TITLE
Config inject doesn't work when `must_exist == true`.

### ISSUE THREAD

**Issue by rcannood** [viash-io/viash#273]
Example `config.vsh.yaml`:

```yaml
functionality:
  name: must_exist
  arguments:
    - name: "--input"
      type: file
      must_exist: true
      example: foo.txt
  resources:
    - type: r_script
      path: script.R
```

Running config inject results in:

```
$ viash config inject config.vsh.yaml
[error] File 'foo.txt' does not exist.
```

Normally this error would be expected when running `viash run config.vsh.yaml --input non_exist.txt` if `non_exist.txt` does not exist. In the context of a config inject, this error is not expected.
