### ISSUE TITLE
.viash_script.sh: line 21: : No such file or directory

### ISSUE THREAD

**Issue by rcannood** [viash-io/viash#278]
running the following:
```bash
nextflow run foo/main.nf --input data/file1.tsv --publish_dir foo_output
```

Results in a strange error:
```
Command error:
 .viash_script.sh: line 21: : No such file or directory
```

```yaml
functionality:
  name: foo
  namespace: vdsl3_tutorial
  arguments:
    - name: "--input"
      alternatives: [ "-i" ]
      type: file
      required: true
      example: "file.tsv"
    - name: "--bar"
      alternatives: [ "-o" ]
      type: file
      required: true
      direction: output
      example: "file.tsv"
  resources:
  - type: bash_script
    path: ./script.sh
    text: |
      grep -v '^#' "$par_input" > "$par_output"
platforms:
  - type: nextflow
    variant: vdsl3
    directives:
      container: ubuntu:20.04
```
