### ISSUE TITLE
`auto.publish` is not taken into account when running a VDSL3 module

### ISSUE THREAD

**Issue by tverbeiren** [viash-io/viash#279]
Given this component:

```yaml
functionality:
  name: a_name
  namespace: a_namespace
  resources:
  - type: bash_script
    path: ./script.sh
    text: |
      grep -v '^#' "$meta_resources_dir"/input.tsv
  - path: input.tsv
    text: |
      # this is a header
      a line in the file
platforms:
  - type: nextflow
```

Building a Nextflow module for it and running the module:

```sh
viash build config.vsh.yaml -p nextflow -o out
nextflow run out/main.nf
```

This results in:

```
Caused by:
  if auto.publish is true, params.publish_dir needs to be defined.
  Example: --publish_dir './output/'. Expression: nextflow.ast.LangHelpers.compareGreaterThan(task.publishDir.size(), 0)
```

Even if we explicitly set `publish: false` in the config, this is happening. If I add `--publish_dir` on the CLI, it works.
