### ISSUE TITLE
Nextflow no longer overriders entrypoint (from 22.10.0 onwards)

### ISSUE THREAD

**Issue by tverbeiren** [viash-io/viash#282]
Given this config:

```yaml
functionality:
  name: issue
  arguments:
    - name: --output
      direction: output
      type: file
      required: true
      example: output.cat
  resources:
    - type: bash_script
      path: script.sh
      text: |
        convert -h > "$par_output"
platforms:
  - type: nextflow
    directives:
      container: dpokidov/imagemagick:7.1.0-50
```

First building this to a Nextflow modules and then running it:

```sh
viash build config.vsh.yaml -p nextflow -o out
NXF_VER=22.10.0 nextflow run out/main.nf --output out.txt --publish_dir output -with-docker
```

This results in a very weird error:

```
Command error:
  convert: no decode delegate for this image format `' @ error/constitute.c/ReadImage/741.
  convert: unrecognized option `-ue' @ error/convert.c/ConvertImageCommand/3197.
```

which turns out to be related to this commit: https://github.com/nextflow-io/nextflow/commit/b3a4bf857cef0a8b16814baf9e13aa9296ca208a.

A temporary workaround exists, by setting `export NXF_CONTAINER_ENTRYPOINT_OVERRIDE=true` but this will be deprecated in the future.

A Viash-enabled solution would be better here IMO.
