### ISSUE TITLE
Should output directories automatically be created?

### ISSUE THREAD

**Issue by rcannood** [viash-io/viash#325]
At the moment, Viash won't automatically create output directories. Example:

Contents of `src/nesting/config.vsh.yaml`:
```yaml
functionality: 
  name: nesting
  arguments:
    - type: file
      name: --input
    - type: file
      name: --output
      direction: output
  resources:
    - type: bash_script
      text: |
        cp $par_input $par_output
platforms:
  - type: nextflow
    directives:
      container: bash:4.0
```

Script:
```bash
#!/bin/bash

# create input folder structure
mkdir -p data/inputs/foo/bar/
echo "Hi" > data/inputs/foo/bar/file.txt

# build components
viash ns build

# run nextflow
nextflow run target/nextflow/nesting/main.nf \
  --input data/inputs/foo/bar/file.txt \
  --output foo/bar/file.txt \
  --publish_dir data/outputs
```

Output:
```
Exporting nesting  =nextflow=> target/nextflow/nesting
All 1 configs built successfully
N E X T F L O W  ~  version 22.04.5
Launching `target/nextflow/nesting/main.nf` [maniac_fourier] DSL2 - revision: 44724e2991
executor >  local (1)
[ad/585d00] process > nesting:nesting_process1 (1) [100%] 1 of 1, failed: 1 ✘
input: [run, [id:run, input:data/inputs/foo/bar/file.txt, output:foo/bar/file.txt]]
Command exit status:
  1

Command output:
  (empty)

Command error:
  cp: cannot create regular file 'foo/bar/file.txt': No such file or directory

Work dir:
  work/ad/585d00cfbd522c0d3fc1b8cdf85883
```

---

Desired outputs:
```
$ ./script.sh 
Exporting nesting  =nextflow=> target/nextflow/nesting
All 1 configs built successfully
N E X T F L O W  ~  version 22.04.5
Launching `target/nextflow/nesting/main.nf` [wise_mclean] DSL2 - revision: 3920fac455
executor >  local (1)
[87/bb9f20] process > nesting:nesting_process1 (1) [100%] 1 of 1 ✔
input: [run, [id:run, input:data/inputs/foo/bar/file.txt, output:foo/bar/file.txt]]
output: [run, work/87/bb9f203da4f79d57d8349cec70e494/foo/bar/file.txt]

$ tree data/outputs
data/outputs
└── foo
    └── bar
        └── file.txt

2 directories, 1 file
```
