### ISSUE TITLE
Check whether certain characters are properly escaped in descriptions

### ISSUE THREAD

**Issue by rcannood** [viash-io/viash#34]
The following characters need to be properly escaped:
```
" ` \ \n $
```

In components like this:
```yaml
functionality:
  description: "here"
  arguments:
    - name: "--test"
      description: "and here"
platforms: # for all three platforms
  - type: docker
  - type: native
  - type: nextflow
```
