### ISSUE TITLE
Change CHANGELOG

### ISSUE THREAD

**Issue by rcannood** [viash-io/viash#341]
Related to #333. What about changing the changelog to a yaml?

```yaml
changelog:
  - name: 0.8.0
    description: A short description of this release.
    summary: |
      Here is a brief summary of what features were added to this release.
    breaking_changes:
      - Onoz
    major_changes:
      - Foo
    minor_changes:
      - Bar
      - Baz
```

WDYT?
