### ISSUE TITLE
Refactor viash test: add main executable 

### ISSUE THREAD

**Issue by rcannood** [viash-io/viash#350]
Let's use the following component as an example:

```yaml
functionality:
  name: example
  arguments:
    - type: file
      name: --input
    - type: file
      name: --output
      direction: output
  resources:
    - type: bash_script
      dest: script.sh
      text: cp $par_input $par_output
  test_resources:
    - type: bash_script
      dest: my_test.sh
      text: |
        echo foo > input.txt
        $meta_executable input.txt output.txt
        [[ -f output.txt ]] || (echo "output does not exist" && exit 1)
        cmp input.txt output.txt || (echo "input and output are different" && exit 1)
        echo "Test succeeded!"
```

What happens when we run `viash test`?

* The main script is built into a `temp_dir/example` executable file.
* The unit test is built into a `temp_dir/test_my_test` executable file.
* The `temp_dir/test_my_test` file is executed

The unit test is kindof treated like a Viash component with the same config as the original component, but with no arguments. The `meta_executable` field is used to run the main script executable. 

Proposal: Wouldn't it make more sense to pass the executable to the unit test by providing it with _one_ input parameter, `executable`? That is, following this proposal, unit tests should use `par["executable"]` to run the underlying script, not `meta["executable"]`.

WDYT?
