### ISSUE TITLE
Referring to the project root in a Viash config

### ISSUE THREAD

**Issue by rcannood** [viash-io/viash#352]
Referring to other files in a Viash config can be a pain because it can only be done through relative paths. Example:

```yaml
test_resources:
  - type: python_script
    path: run_test.py
  - path: ../../../resources_test/pbmc_1k_protein_v3
```

It would be great if we could refer to the root of a project somehow, but there are multiple approaches.

## Option 1: Use a `/` at the beginning of a path

If the path begins with a `/`, then Viash will relativize the file against the directory of the `_viash.yaml`. If no `_viash.yaml` is found, a helpful error message is thrown.

Example:

```yaml
test_resources:
  - type: python_script
    path: run_test.py
  - path: /resources_test/pbmc_1k_protein_v3
```

Pros:
  - This is standard notation in other frameworks (e.g. quarto)
  - It enforces good behaviour (i.e. don't refer to files outside the scope of the project)

Cons:
  - It's no longer possible to temporarily use an absolute path as part of your project (even though this is bad behaviour, you might want to do this while debugging something) -- Example `path: /tmp/example_bug/foo.txt`

A workaround to mitigate the con could be to have a separate notation for absolute paths. For example, using `file:///tmp/example_bug/foo.txt` could be used to forcibly specify an absolute path.

## Option 2: With variables

Allow defining variables which can be used in your yaml files. We could use a syntax similar to GitHub Actions and Azure DevOps.

Example:

```yaml
test_resources:
  - type: python_script
    path: run_test.py
  - path: ${{ project.dir }}/resources_test/pbmc_1k_protein_v3
```

Pro:
  - Also common notation in other frameworks
  - It allows for making it possible in the future for users to define a custom set of variables. For example, by adding `variables: [foo: bar]` to `_viash.yaml`, the user could use `${{variables.foo}}` in their config.

Con:
  - Adds more complexity to the Viash spec, because the variables in the config would need to be resolved before being able to do a `viash config view`.

## Option 3: With config mods

Same as before, but using the notation for resolving config mods.

Example:

```yaml
test_resources:
  - type: python_script
    path: run_test.py
  - path: ${{ .info.project_dir }}/resources_test/pbmc_1k_protein_v3
```

Pro:
  - Users only need to learn one notation (that is, the config mod one) to be able to do a variety of things:
    - Refer to the root dir of the repo: `path: ${{ .info.project_dir }}/resources_test/pbmc_1k_protein_v3`
    - Override version number with a config mod: `viash ns build -c '.functionality.version := "0.1.0"'`
    - Define an output format of `viash config view` and `viash ns list`:
      - `viash config view --format '{ "name": .functionality.name }'`
      - `viash ns list --format '{ "name": .functionality.name }'`

Con:
  - Even more complexity in the config might lead to edgecase bugs.

## Discussion

Are there any other proposals?

I'm leaning towards option 1, but I think option 3 is also interesting
