### ISSUE TITLE
Viash removes empty fields in the `info` section of the config file

### ISSUE THREAD

**Issue by KaiWaldrant** [viash-io/viash#386]
fields that are empty in the `info` section should not be removed as they are added on purpose.

```yaml
functionality:
  name: "majority_vote"
  namespace: "label_projection/control_methods"
  description: "Baseline method using majority voting"
  info:
    subtype: negative_control
    method_name: Majority Vote
    v1_url: openproblems/tasks/label_projection/methods/baseline.py
    v1_commit: b460ecb183328c857cbbf653488f522a4034a61c
    variants:
      majority_vote:
    preferred_normalization: counts
```

when executing a `config view` the `variants` is empty.
```yaml
    info:
      subtype: "negative_control"
      method_name: "Majority Vote"
      v1_url: "openproblems/tasks/label_projection/methods/baseline.py"
      v1_commit: "b460ecb183328c857cbbf653488f522a4034a61c"
      variants: {}
```
