### ISSUE TITLE
Fix parent value in config view

### ISSUE THREAD

**Issue by rcannood** [viash-io/viash#397]
Take for example this config file:

```yaml
functionality:
  name: foo
  resources:
    - type: python_script
      path: script.py
    - path: /_viash.yaml
```

Running a config view results in the following:

```bash
$ viash config view src/foo/config.vsh.yaml 
```

```yaml
functionality:
  name: "foo"
  resources:
  - type: "python_script"
    path: "script.py"
    is_executable: true
    parent: "file:/home/rcannood/project/src/foo/config.vsh.yaml"
  - type: "file"
    path: "_viash.yaml"
    parent: "file:///home/rcannood/project/foo/"
```

I expect the parent of the python script to be `"file:/home/rcannood/project/src/foo/"` and not `"file:/home/rcannood/project/src/foo/config.vsh.yaml"`, even though in java.net.URI terms this not affect relative file resolution:

```scala
import java.net.URI

val uri = new URI("file:/home/rcannood/project/src/foo/")
uri.resolve("script.py") # results in "file:/home/rcannood/project/src/foo/script.py"

val uri2 = new URI("file:/home/rcannood/project/src/foo/config.vsh.yaml")
uri2.resolve("script.py") # also results in "file:/home/rcannood/project/src/foo/script.py"
```

I would propose stripping the `config.vsh.yaml` from the parent field such that path always points to a directory and not a file.
