### ISSUE TITLE
Add default labels to nextflow config

### ISSUE THREAD

**Issue by rcannood** [viash-io/viash#410]
In the `renderNextflowConfig()` function, it'd be great if we could add default profiles, e.g.:

```
process {
  withLabel: lowmem { memory = 4.Gb }
  withLabel: lowcpu { cpus = 4 }
  withLabel: midmem { memory = 25.Gb }
  withLabel: midcpu { cpus = 10 }
  withLabel: highmem { memory = 50.Gb }
  withLabel: highcpu { cpus = 20 }
  withLabel: vhighmem { memory = 100.Gb }
  withLabel: vhighcpu { cpus = 40 }
}
```

Alternative:

```
process {
  withLabel: mem5gb { memory = 5.Gb }
  withLabel: mem10gb { memory = 10.Gb }
  withLabel: mem20gb { memory = 20.Gb }
  withLabel: mem50gb { memory = 50.Gb }
  withLabel: mem100gb { memory = 100.Gb }
  withLabel: mem200gb { memory = 200.Gb }
  withLabel: mem500gb { memory = 500.Gb }
  ...
}
```

How could we allow adding these defaults but being able to override them if need be?

# Map syntax

```
platforms:
  - type: nextflow
    auto:
      labels:
        lowmem: "memory = 4.Gb"
        lowcpu: "cpus = 4"
        # ... other labels
```

If we use this notation, I'd expect all labels to be replaced with the labels provided in the config. That is, the code above would remove all labels and only define `lowmem` and `lowcpu`.

# Verbatim syntax

Either with or without the `process { ... }`. 

```
platforms:
  - type: nextflow
    auto:
      include_in_config: |
        process {
          withLabel: lowmem { memory = 4.Gb }
          withLabel: lowcpu { cpus = 4 }
          withLabel: midmem { memory = 25.Gb }
          withLabel: midcpu { cpus = 10 }
          withLabel: highmem { memory = 50.Gb }
          withLabel: highcpu { cpus = 20 }
          withLabel: vhighmem { memory = 100.Gb }
          withLabel: vhighcpu { cpus = 40 }
        }
```

I'm not a big fan of doing it this way, though something like `include_in_config` could be used for in other scenarios as well.
