### ISSUE TITLE
Tracking software versions

### ISSUE THREAD

**Issue by rcannood** [viash-io/viash#416]
I was experimenting with listing version numbers of Docker images so they can be documented. For reference, I used the following code:

```r
docker_pkg_version <- function(container_id) {
  # Commands to detect package versions
  commands <- list(
    apt = "dpkg-query --showformat='${Package} ${Version}\\n' --show",
    apk = "apk info --all | grep -e ^P -e ^V | awk 'NR%2{printf \"%s \", $0; next} 1'",
    yum = "yum list installed | awk 'NR>1 {print $1, $2}'",
    r_packages = "Rscript -e 'installed.packages()[,c(1,3)]'",
    python_packages = "pip freeze"
  )

  # Execute the commands inside the Docker container and store the results
  package_versions <- lapply(commands, function(command) {
    tryCatch({
      docker_command <- paste("docker run", container_id, command)
      system(docker_command, intern = TRUE, ignore.stderr = TRUE)
    }, error = function(e) {
      character(0)
    })
  })

  # Print the detected package versions
  names(package_versions) <- names(commands)

  package_versions
}
```

This could be executed immediately after a Docker image has been built (maybe not by default, but definitely during a `main_build` and a release). This information could then be stored inside the viash config.

Additionally, we should add a way for adding versions of custom cli tools, such as:

```
resources:
  - type: bash_script
    path: script.sh
    usage: main
  - type: bash_script
    path: version.sh
    usage: version
test_resources:
  - type: bash_script
    path: test.sh
    usage: test
```

(Would need to find a better name for 'usage')
