### ISSUE TITLE
Usage types

### ISSUE THREAD

**Issue by rcannood** [viash-io/viash#435]
It's come up a few times that it might be useful to have different ways of using resources. This issue is a collection of all of the individual ideas.

## Defaults
A script in the resources section would have `usage: main` as the default, while a script in the test_resources would have `usage: test` as the default.

```yaml
resources:
  - type: bash_script
    path: script.sh
    usage: main # default
test_resources:
  - type: bash_script
    path: test.sh
    usage: test # default
```

## Version numbers
Posted in #416

```yaml
resources:
  - type: bash_script
    path: script.sh
    usage: main
  - type: bash_script
    path: version.sh
    usage: version
test_resources:
  - type: bash_script
    path: test.sh
    usage: test
```

## Stub
Posted in #243 ?

```yaml
resources:
  - type: nextflow_script
    path: script.nf
    entrypoint: mywf
    usage: main # default
  - type: nextflow_script
    path: script.nf
    entrypoint: mystub
    usage: stub
test_resources:
  - type: nextflow_script
    path: script.nf
    entrypoint: mytest
    usage: test # default
```

## Snippets

As an alternative to how we currently recommend [using helper functions](https://viash.io/guide/component/use-helper-functions.html), we might also allow users prepend their script with a different file using the following.

```yaml
resources:
  - type: bash_script
    path: script.sh
    usage: main
  - type: bash_script
    path: helper_functions.sh
    usage: snippet
```
