### ISSUE TITLE
Allow defining mutually exclusive and mutually inclusive arguments in the viash config

### ISSUE THREAD

**Issue by DriesSchaumont** [viash-io/viash#497]
It would be nice to have functionality in the viash that allow two or more arguments to _not_ be defined at the same time (mutually exclusive) or that force a group of arguments to be defined if one or members member of that group is defined (mutually inclusive?).

Inspiration for python: 
https://docs.python.org/3/library/argparse.html#mutual-exclusion

**Comment by Grifs** [comment]
```yaml
functionality:
  name: test
  arguments:
    - name: foo
      type: string
    - name: bar
      type: string
    - name: baz
      type: string
```

```yaml
functionality:
  name: test
  arguments:
    - name: foo
      type: string
      require: [ 'bar' ]
      require_not: [ 'baz' ]
    - name: bar
      type: string
    - name: baz
      type: string
```

could result in something like the following code to be added in the bashwrapper:

```bash
if [ -n "$VIASH_PAR_FOO" ] && [ -z "$VIASH_PAR_BAR" ]; then
  # throw error
fi
if [ -n "$VIASH_PAR_FOO" ] && [ -n "$VIASH_PAR_BAZ" ]; then
  # throw error
fi
```

This could possibly be quite straight forward to implement.

Note: This allows using `bar` without having the requirement of `foo` being specified.
If this needs to be checked, the config would need to be adjusted to e.g.

```yaml
functionality:
  name: test
  arguments:
    - name: foo
      type: string
      require: [ 'bar' ]
      require_not: [ 'baz' ]
    - name: bar
      type: string
      require: [ 'foo' ]
    - name: baz
      type: string
```

This can potentially become tricky to correctly list all inner-dependencies.
However, if there are multiple arguments that need to be used together, selecting a main argument can make things slightly easier.

```yaml
functionality:
  name: test
  arguments:
    - name: foo
      type: string
      require: [ 'bar', 'baz', 'qux' ]
    - name: bar
      type: string
      require: [ 'foo' ]
    - name: baz
      type: string
      require: [ 'foo' ]
    - name: qux
      type: string
      require: [ 'foo' ]
```

This is functionally equivalent to each argument specifying all other arguments.

**Comment by Grifs** [comment]
Another option could be to add a general argument validation field where (optionally) multiple validations can be added. However, this might become unwieldy in case of multiple possible conditions:

```yaml
functionality:
  name: test
  arguments:
    - name: foo
      type: string
    - name: bar
      type: string
    - name: baz
      type: string
  validation:
    - foo & qux & !bar & !baz
    - bar & qux & !foo & !baz
    - baz & qux & !foo & !baz
    - qux & foo | bar | baz
```
won't work as there are contradicting statements.
This specific validation could perhaps be rewritten as:
```yaml
validation:
  - foo ^ bar ^ baz
  - (foo | bar | baz) & qux
```
However, it feels like there might be significant short comings given that it misses conditional statements (only validate if a certain argument is specified).
