### ISSUE TITLE
Omit `functionality` in config

### ISSUE THREAD

**Issue by rcannood** [viash-io/viash#500]
Hendrik mentioned potentionally omitting the `functionality:` from the config. That is, the config now becomes:

```yaml
name: xxx
namespace: ...
arguments: ...
resources: ...
platforms:
  ...
```

Currently:

```yaml
functionality:
  name: xxx
  namespace: ...
  arguments: ...
  resources: ...
platforms:
  ...
```
