### ISSUE TITLE
Suggestion: Add optional 'example usage' string that gets printed out below the description of a component in config yaml

### ISSUE THREAD

**Issue by BlackDragonBE** [viash-io/viash#53]
For example, take this yaml:

```yaml
functionality:
  name: hello_world
  description: A very simple 'Hello world' component.
  example: visitor. --greeter="Greetings"
  arguments:
  - type: string
    name: input
    multiple: true
    multiple_sep: " "
  - type: string
    name: --greeter
    default: "Hello world!"
  resources:
  - type: bash_script
    path: script.sh
  tests:
  - type: bash_script
    path: test.sh
platforms:
  - type: native
  - type: docker
    image: bash:4.0
  - type: docker
    id: alpine
    image: alpine
    setup:
      - type: apk
        packages: [ bash ]
```

If you'd run `viash run config.vsh.yaml -- --help` on this, this might be the possible output:  
   
```
A very simple 'Hello world' component.
Example usage:
viash run config.vsh.yaml -- visitor. --greeter="Greetings"

Options:
    string1 string2 ...
        type: string, multiple values allowed

    --greeter=string
        type: string, default: Hello world!
```

In a nutshell, it adds an example by adding `viash run config.vsh.yaml --` before the example defined in yaml.
