### ISSUE TITLE
split up arguments into inputs and outputs

### ISSUE THREAD

**Issue by rcannood** [viash-io/viash#55]
Current:
```yaml
functionality:
  arguments:
    - type: file
      direction: input
      name: "--input"
    - type: file
      direction: output
      name: "--output"
    - type: string
      name: "--str"
      default: foo
```

Proposal:
```yaml
functionality:
  inputs:
    - name: "--input"
  outputs:
    - name: "--output"
  arguments:
    - type: string
      name: "--str"
      default: foo
```

Edit: updated this description based on Toni's proposal at the bottom.

**Comment by tverbeiren** [comment]
In principle those are two different representations of the same thing. However, there is a difference: the array of arguments in the current implementation has an order to it.

If we simply wrap a binary (no custom script) and the underlying tool requires positional arguments the proposal does not contain the order anymore. The current version does.

**Comment by BlackDragonBE** [comment]
One way of mitigating the argument order issue is adding an optional "order" int attribute . The argument order for the final component could then use those to sort the array.  
However, that does complicate the setup of the config file.

**Comment by rcannood** [comment]
Hmm. If order is an issue then keeping the config the way its currently done makes more sense. 

Does wrapping a binary without script still work? Is it something we want to continue supporting in the future?

**Comment by rcannood** [comment]
In talking it over with @tverbeiren, it might be a good idea to keep the arguments ordered, because we don't know whether we might need it in the future.

Adding an `order: 1` to each argument rather than needing to specify the direction the argument uses, might reduce the amount of typing that needs to be done in 99.9% of viash components. 

Here's another alternative! We support both 'inputs/outputs' and 'arguments'. Internally, viash will create and use the following list:
```scala
case class Functionality(..., inputs, outputs, arguments, ...) {
  val internal_args = arguments +++
    inputs.map(_.copy(direction = Input)) +++ 
    outputs.map(_.copy(direction = Output)
}
```

most people can then use inputs and outputs. If order is important, you can use arguments.

@BlackDragonBE @tverbeiren Thoughts?

**Comment by tverbeiren** [comment]
Alternative suggestion: We keep arguments and allow for two different representations of arguments of the type `{type: file, direction: input/output}`. The following two would be identical (up to the implicit order, that is):

```yaml
functionality:
  arguments:
    - type: file
      direction: input
      name: "--input"
    - type: file
      direction: output
      name: "--output"
    - type: string
      name: "--modifier"
```

With explicit `inputs` and `outputs`, implicit `type: file` for those and probably also `required: true`:

```yaml
functionality:
  inputs:
    - name: "--input"
  outputs:
    - name: "--output"
  arguments:
    - type: string
      name: "--modifier"
```
