### ISSUE TITLE
Support install dependencies from scripts and conda?

### ISSUE THREAD

**Issue by ShixiangWang** [viash-io/viash#567]
Hi,

I just found viash, it's shiny. I have some questions after reading the docs.

Considering a pipeline project I am focusing on, I need to use conda to construct different environments to install different software. The steps to install the environments are stored in a shell script or makefile. How should I declare such cases in `setup` to make sure they could be executed in a new Linux or construction of the Docker image? 

e.g., a bash command to install the Circexplorer2.

```
mamba create -n Circexplorer2 -c conda-forge -c bioconda -y python=3.7 bwa &&\
 source activate Circexplorer2 &&\
 pip install circexplorer2

```

Best,
Shixiang

**Comment by rcannood** [comment]
Hi @ShixiangWang !

At the moment, there is no helper class for setting up a conda environment, but I'm interested in determining what this might look like.

Do you think something like this could make sense?

```bash
setup:
  - type: conda
    name: myenv
    channels: [conda-forge, bioconda]
    python_version: 3.7
    packages: [bwa, circexplorer]
```

This would get translated as a dockerfile as follows:

```bash
RUN if ! conda info --envs | grep -q '^myenv\s'; then \
      mamba create -n myenv -c conda-forge -c bioconda -y python=3.7 && \
        echo "source /opt/conda/etc/profile.d/conda.sh && conda activate myenv" >> /root/.bashrc;
    fi
RUN /opt/conda/envs/myenv/bin/pip install bwa circexplorer2
fi
```

----

Until something like this is implemented, note that you can do this using a set of run commands ([see docs](https://viash.io/reference/config/platforms/docker/setup/dockerRequirements.html)). For example:

```yaml
functionality:
  name: foo
platforms:
  - type: docker
    image: condaforge/mambaforge:4.10.1-5
    setup: 
      - type: docker
        env: ENV_NAME=Circexplorer2
        run: |
          mamba create -n $ENV_NAME -c conda-forge -c bioconda -y python=3.7 && \
            /opt/conda/envs/$ENV_NAME/bin/pip install bwa circexplorer2
```
