### ISSUE TITLE
`Unexpected error [StackOverflowError]` when a workflow `functionality.name` is identical to the entrypoint.

### ISSUE THREAD

**Issue by DriesSchaumont** [viash-io/viash#583]
When creating a workflow with

```
functionality:
   name: "foo"
...
resources:
    - type: nextflow_script
      path: main.nf
      entrypoint: foo
```

causes a recursive loop that leads to a `StackOverflowError`.
I think we can catch this error during build.
