### ISSUE TITLE
No error when using `dependencies:` in the root of the config instead of using `functionality.dependencies`.

### ISSUE THREAD

**Issue by DriesSchaumont** [viash-io/viash#584]
Using 

```yaml
functionality:
  name: foo
  ...
depdendencies: 
  - name: bar
```
Instead of 
```yaml
functionality:
  name: foo
  ...
  depdendencies: 
    - name: bar
```
Is being parsed by viash to
```yaml
functionality:
  name: foo
  ...
```
without any errors.
