### ISSUE TITLE
Required repository name when defined directly in a dependency

### ISSUE THREAD

**Issue by Grifs** [viash-io/viash#599]
When a user defines a repository in a dependency, the user must also define the `name` of the repository. This is unintuitive as the name is never used for anything.

Doesn't work:
```
  dependencies: 
    - name: qc/multiqc
      repository: 
        type: vsh
        repo: openpipelines-bio/openpipeline
        tag: 0.12.1
```

Works:
```
  dependencies: 
    - name: qc/multiqc
      repository: 
        name: literally_anything
        type: vsh
        repo: openpipelines-bio/openpipeline
        tag: 0.12.1
```

Furthermore, the generated error doesn't exactly highlight the fact that a field is missing:
```
❯ viash build src/workflows/parallel_qc/config.vsh.yaml
viash: Error parsing, invalid Viash Config content in file 'file:/Users/toni/code/projects/viash-hub/demo/src/workflows/parallel_qc/config.vsh.yaml'.
Details:
Invalid data fields for ViashhubRepository.
{
  "type" : "vsh",
  "repo" : "openpipelines-bio/openpipeline",
  "tag" : "0.12.1"
}
```
I'm not yet sure what the best way would be for the error output to assist the user in discovering what the issue is with the provided config (section).
