### ISSUE TITLE
local dependency sugar syntax

### ISSUE THREAD

**Issue by Grifs** [viash-io/viash#608]
`repository: local` should be picked up as sugar syntax to define a local dependency

Currently the notation for step2 doesn't work
```
  dependencies:
    - name: step1 # local is implicit
    - name: step2
      repository: local
    - name: step3
      repository: mylocal
  repositories:
    - name: mylocal
      type: local
```
