### ISSUE TITLE
Extend resources and setup

### ISSUE THREAD

**Issue by rcannood** [viash-io/viash#61]
In some cases, it could be interesting to allow for build-time resources (`.functionality.build_resources`) as well as test-specific setup (`.platforms[].test_setup`).

In the meantime, we can uniformise the naming of the testing resources from `.functionality.tests` to `.functionality.test_resources`.

Currently:

```yaml
functionality:
  ...
  resources: [ ... ] 
  tests: [ ... ]
platforms:
  - type: docker
    setup: [ ... ]
```

Proposed format
```yaml
functionality:
  ...
  resources: [ ... ] 
  build_resources: [ ... ]
  test_resources: [ ... ]
platforms:
  - type: docker
    setup: [ ... ]
    test_setup: [ ... ] # steps to be executed after the steps in 'setup'
```
