### ISSUE TITLE
validate yaml configs

### ISSUE THREAD

**Issue by rcannood** [viash-io/viash#62]
circe doesn't validate non-existing fields in the yaml config by default. For example:

```yaml
functionality:
  name: test
  4rguments:
    - name: "input"
      type: string
  resources:
    - type: bash_script
      text: echo $par_input
      dest: script.sh
```

When running the following command, viash doesn't throw an error or warning:

```
$ viash run config.vsh.yaml -- hello

$ viash run config.vsh.yaml -- -h
test <not versioned>

Options:
```

Apparently this can be solved with the `.withStrictDecoding` configuration (circe/circe#1117).
