### ISSUE TITLE
[BUG] Unclear assertion error from viash config file

### ISSUE THREAD

**Issue by KaiWaldrant** [viash-io/viash#674]
### What happened?

An assertion error was given but it was unclear what the problem was.

After some investigation it was clear that the `''` was causing the assertion error. changing these to `""` fixed the error.

### Steps to reproduce

Contents of `config.vsh.yaml`:

```yaml
platforms:
  - type: docker
    image: ghcr.io/openproblems-bio/base_r:1.0.3
    setup:
      - type: apt
        packages: cmake
      - type: r
        cran: rliger
        script:
        - install.packages('RcppPlanc', repos = c(linux = 'https://welch-lab.r-universe.dev/bin/linux/jammy/4.3', sources = 'https://welch-lab.r-universe.dev', cran = https://cloud.r-project.org'))
```

### Expected behavior

Output the reason why the assertion occured

### Relevant log output

```
viash: Error parsing, invalid Viash Config content in file 'file:/home/kai/Documents/openproblems/openproblems-v2/src/tasks/batch_integration/methods/liger/config.vsh.yaml'.
Details:
assertion failed
```

### Version

- Viash: 0.8.0

### Confirmation

- [X] I have searched the existing issues to make sure this is not a duplicate.
- [X] I have provided clear and concise information about the bug.
