### ISSUE TITLE
[BUG] file arguments with multiple true require a wildcard but still end up being lists

### ISSUE THREAD

**Issue by rcannood** [viash-io/viash#706]
### What happened?

When defining a file argument with multiple: true and direction: output, viash 0.8.6 expects any values passed to that argument to contain a wildcard. E.g.

```yaml
functionality:
  name: test
  arguments:
    - type: file
      name: --output
      direction: output
      multiple: true
      must_exist: false
  resources:
    - type: python_script
      text: |
        print(par)
```

```bash
$ viash run config.vsh.yaml -- --output foo.txt

[error] --output has to be a path containing a wildcard, e.g. output_*.txt. Use --help to get more information on the parameters.
```

However, one would then perhaps expect that `par["output"]` would be a string containing that wildcard, not a list of a string.

```bash
$ viash run config.vsh.yaml -- --output foo*.txt
{'output': ['foo*.txt']}
```

Especially given that viash now does not allow passing multiple values:

```bash
$ viash run config.vsh.yaml -- --output foo*.txt --output bar*.txt
[error] Bad arguments for option '--output': 'foo*.txt' & 'bar*.txt' - you should provide exactly one argument for this option.
Files and logs are stored at '/tmp/viash_test12865580121557640188'
```

Thus, we need to change viash such that it passes `par` to the script as `{"output": "foo*.txt"}`.

### Steps to reproduce

/

### Expected behavior

/

### Relevant log output

/

### Version

Viash 0.8.6

### Confirmation

- [X] I have searched the existing issues to make sure this is not a duplicate.
- [X] I have provided clear and concise information about the bug.
