### ISSUE TITLE
[BUG] build_info lists wrong executable

### ISSUE THREAD

**Issue by rcannood** [viash-io/viash#716]
### What happened?

The build info of a nextflow module currently reads:

```yaml
build_info:
  config: "src/arriba/config.vsh.yaml"
  runner: "nextflow"
  engine: "docker|native"
  output: "target/nextflow/arriba"
  executable: "target/nextflow/arriba/arriba"
  viash_version: "0.9.0-RC3"
  git_commit: "8ef02fa93ed3bad6581142aaf9cd38c2554fe738"
  git_remote: "https://github.com/viash-hub/biobase"
```

However, this should probably be
```yaml
  executable: "target/nextflow/arriba/main.nf"
```

Or ... perhaps call it a nextflow_module, for the sake of clarity?

### Steps to reproduce

/

### Expected behavior

/

### Relevant log output

/

### Version

/

### Confirmation

- [X] I have searched the existing issues to make sure this is not a duplicate.
- [X] I have provided clear and concise information about the bug.
