### ISSUE TITLE
[BUG] Documentation improvements

### ISSUE THREAD

**Issue by rcannood** [viash-io/viash#726]
### What happened?

There are parts of the documentation that could be improved:

* [Argument groups](https://viash.io/reference/config/functionality/argumentGroup.html) needs an example, e.g.
  ```yaml
  argument_groups:
    - name: Inputs
      description: Arguments related to input files.
      arguments: ...
  ...etc...
  ```

* [Author](https://viash.io/reference/config/functionality/author.html) example should be more complete, e.g.

  ```yaml
  authors:
    - name: Jane Doe
      role: [author, maintainer]
      email: jane@doe.com
      info:
        github: janedoe
        twitter: janedoe
        orcid: XXAABBCCXX
        groups: [ one, two, three ]
  ```

* [Computational requirements](https://viash.io/reference/config/functionality/computationalRequirements.html) needs an example:

  ```yaml
  requirements:
    commands: [...]
    cpus: 10
    memory: 10GB
  ```

* [Dependency](https://viash.io/reference/config/functionality/dependencies/): Add an example from the perspective of the root of the config?

* [Runners](https://viash.io/pr-preview/pr-89/versioned/0_9_0_RC/reference/config/runners/): Should get a better explanation of what adding runners does, at a high level.

* [Engines](https://viash.io/pr-preview/pr-89/versioned/0_9_0_RC/reference/config/engines/): Should get a better explanation of what adding engines does, at a high level.

* [Links](https://viash.io/pr-preview/pr-89/versioned/0_9_0_RC/reference/config/links.html): Example should be from the perspective of the config, that is, should be prefixed with `links:`.

* [References](https://viash.io/pr-preview/pr-89/versioned/0_9_0_RC/reference/config/references.html): Example should be from the perspective of the config, that is, should be prefixed with `references:`. Also, perhaps change the description to something like: "A list of scholarly sources or publications relevant to the tools or analysis defined in the component. This is important for attribution, scientific reproducibility and transparency."

### Steps to reproduce

/

### Expected behavior

/

### Relevant log output

/

### Version

Viash 0.9

### Confirmation

- [X] I have searched the existing issues to make sure this is not a duplicate.
- [X] I have provided clear and concise information about the bug.
