### ISSUE TITLE
[FEATURE INCUBATOR] Rework types

### ISSUE THREAD

**Issue by rcannood** [viash-io/viash#735]
### Feature summary

While looking at a simple [CWL workflow](https://bitbucket.org/CRSwDev/cwl/src/master/v2.2.1/Extra_Utilities/make_rhap_reference_2.2.1.cwl) I found it quite interesting that CWL has a different way of specifying input/output types.

Example Viash:

```yaml
arguments:
  - name: --multiple_input
    type: file
    required: true
    multiple: true
  - name: --optional_string
    type: string
    required: false
  - name: --optional_multiple_integer
    type: integer
    multiple: true
```

CWL:

```cwl
inputs: 
    Multiple_input:
        type: File[]
        inputBinding:
            prefix: --multiple_input
    Optional_string:
        type: string?
        inputBinding:
            prefix: --optional_string
    Optional_multiple_integer:
        type: int[]?
        inputBinding:
            prefix: --optional_multiple_integer
```

### Feature description

I'd like to pitch adding `type: file[]`, `type: file?` and `type: file[]?` as sugar syntax for:

* `file[]`: `{type: file, multiple: true, required: true}`
* `file?`: `{type: file, multiple: false, required: false}`
* `file[]?`: `{type: file, multiple: true, required: false}`
* `file`: `{type: file, multiple: false, required: false}`

Ohno. This is a breaking change!

:(

### Why is this feature beneficial?

To me, it feels like a much easier way to show what the data type of the `par` object will be inside the script.

Hendrik mentioned that he had some concerns introducing unnecessary sugar syntax, which I totally understand.

### Confirmation

- [X] I have searched the existing issues to make sure this is not a duplicate request.
- [X] I have provided clear and concise information about the feature.
