### ISSUE TITLE
nxf: no way of controlling optional output files

### ISSUE THREAD

**Issue by rcannood** [viash-io/viash#74]
Example component `src/bar/config.vsh.yaml`:

```yaml
functionality:
  name: bar
  arguments:
    - name: "--input"
      type: file
      example: input.txt
    - name: "--output"
      type: file
      direction: output
      required: true
      example: output.txt
    - name: "--optional_output"
      type: file
      direction: output
      required: false
      example: optional.txt
  resources:
    - type: r_script
      dest: script.R
      text: |
        lines <- readr::read_lines(par$input)
        readr::write_lines(lines, par$output)
        if (!is.null(par$optional_output)) {
          if (tools::file_ext(par$optional_output) != "txt") {
            stop("Error: unknown file extension")
          }
          readr::write_lines(lines, par$optional_output)
        }
platforms:
  - type: docker
    image: rocker/tidyverse:4.0.5
  - type: nextflow
```

Running this component in nextflow with script:

```
nextflow.enable.dsl=2

include  { bar } from "./target/nextflow/bar/main.nf" params(params)

workflow {
    main:
    if (!params.containsKey("input") || params.input == "") {
        exit 1, "ERROR: Please provide a --input parameter."
    }
    
    output_ = Channel.fromPath(params.input) \
        | map { [ "foo", it, params ] } \
        | view { [ "DEBUG", it[0], it[1] ] } \
        | bar
}
```

Will produce an error because according to the logs, the component is being executed with the command `bar --input 'nextflow.config' --output 'foo.bar.txt' --optional_output 'foo.no_default_value_configured'`. In order words, nextflow is extracting an extension for a non-provided non-required argument. 

Reproducible example in attachment:

[example.zip](https://github.com/viash-io/viash/files/6765989/example.zip)
