### ISSUE TITLE
[BUG] `boolean_true` and `boolean_false` should be allowed `multiple: true`

### ISSUE THREAD

**Issue by rcannood** [viash-io/viash#749]
### What happened?

Right now, boolean_true and boolean_false are not allowed `multiple: true`. However, I suppose that you should be able to do something like:

```
arguments:
  - type: boolean_true
    name: --verbose
    multiple: true
```

`boolean_true` values will then only be able to return a list of true values, while `boolean_false` will only be able to list of false values.

### Steps to reproduce

/

### Expected behavior

/

### Version

/

### Confirmation

- [X] I have searched the existing issues to make sure this is not a duplicate.
- [X] I have provided clear and concise information about the bug.
