### ISSUE TITLE
[BUG] Issue with schema

### ISSUE THREAD

**Issue by rcannood** [viash-io/viash#765]
### What happened?

The json schema has a wrong type specification for the repositories. According to the schema, the repositories field in the following yaml is invalid:

```yaml
repositories:
  - name: openproblems_v2
    type: github
    repo: openproblems-bio/openproblems-v2
    tag: main_build
```

The reason being that `type` must be `githubwithname` or `viashhubwithname`.

### Steps to reproduce

Install the [Viash VS Code extension](https://marketplace.visualstudio.com/items?itemName=data-intuitive.viash) and open up any Viash 0.9.0-RC7 project which has a repository.

### Expected behavior

The schema needs to contain:

```yaml
      type:
        description: "A Git repository where remote dependency components can be found."
        const: "git"
```

And not

```yaml
      type:
        description: "A Git repository where remote dependency components can be found."
        const: "gitwithname"
```

### Version

Viash 0.9.0-RC7

### Confirmation

- [X] I have searched the existing issues to make sure this is not a duplicate.
- [X] I have provided clear and concise information about the bug.
