### ISSUE TITLE
BashWrapper: boolean parameters defaults are not working

### ISSUE THREAD

**Issue by rcannood** [viash-io/viash#79]
For the following arguments:
```yaml
    - name: "--flag_true"
      type: boolean_true
      description: "Flag true"
    - name: "--flag_false"
      type: boolean_false
      description: "Flag false"
    - name: "--boolean"
      type: boolean
      description: "Boolean"
      default: true
```

Viash will generate a default for flag_true and flag_false, but not for boolean:
```bash
if [ -z "$VIASH_PAR_FLAG_TRUE" ]; then
  VIASH_PAR_FLAG_TRUE="false"
fi
if [ -z "$VIASH_PAR_FLAG_FALSE" ]; then
  VIASH_PAR_FLAG_FALSE="true"
fi
```
