### ISSUE TITLE
Requiring packages in javascript scripts is not working as they're installed as global tools

### ISSUE THREAD

**Issue by BlackDragonBE** [viash-io/viash#89]
## Problem

Javascript scripts that require packages when running in a Docker container won't be able to find the package as it's installed globally as a tool. For example, this line won't be able to execute:

 ```javascript
 const needle = require('needle')
 ```

 Trying to run a script with the require statement above results in this error being thrown:

```
node:internal/modules/cjs/loader:927
  throw err;
  ^

Error: Cannot find module 'needle'
```

 Even though it was installed globally via the config file:
 
 ```yaml
functionality: 
  name: md_url_checker_js
  version: 0.8
...
 platforms:
  - type: docker
    image: node:15-buster
    setup:
      - type: apt
        packages: [ bash ]
      - type: javascript
        npm: [ needle, markdown-link-extractor ]
``` 

Proof that `needle` is installed by generating a list of installed global npm packages:

```bash 
docker run md_url_checker_js:0.8 npm list -g

/usr/local/lib
+-- markdown-link-extractor@1.3.0
+-- needle@3.0.0
`-- npm@7.7.6
```

## Steps to reproduce

I've included a minimal example as an attachment that can be run with viash and will fail as the `needle` module  will not be found.

Link to zip:  
[javascript-global-error.zip](https://github.com/viash-io/viash/files/7286113/javascript-global-error.zip)

## Proposed solution

At the moment, the command that viash executes for installing npm packages is as follows ([source](https://github.com/viash-io/viash/blob/main/src/main/scala/com/dataintuitive/viash/platforms/requirements/JavaScriptRequirements.scala)):

```bash
npm install -g PACKAGE
```

By adding --save at the end, this will install the package locally, allowing it to be referenced in node.js scripts ([source](https://stackoverflow.com/a/42445768)):

```
npm install -g PACKAGE --save
```
