### ISSUE TITLE
Is there anyway to add additional parameters when building a docker backend

### ISSUE THREAD

**Issue by chthub** [viash-io/viash#90]
When I use `docker build`, I can specify a parameter `network` like this:
```
docker build --network=host ...
```
**but how I can do this by the configs in `config.vsh.yaml`?**
I tried to do this, but it didn't work:
```
platforms:
  - type: docker
    image: dataintuitive/randpy:py3.8
    setup:
      - type: docker
        network: 
          - host
      - type: python
        packages:
          - umap-learn
```
