### ISSUE TITLE
Validation of input/output arguments

### ISSUE THREAD

**Issue by rcannood** [viash-io/viash#93]
It'd be useful to be able to add some validation of input/output arguments. Specifically, if we have a lot of AnnData / Muon files, it'd be useful to add some validation w.r.t. the expected fields.

## Option 1: Implement a separate components

This is what is currently already possible -- add a separate component which acts as a gateway to verify whether files passing through it match a certain interface. In terms of Nextflow, this would look something like:

```nextflow
channel
  | gateway_interface1
  | method1
  | gateway_interface2
  | method2
```

## Option 2: Add separate 'muon' and 'anndata' filetypes

It would be possible to add additional argument types (e.g. through plugins) which allow specifying additional fields in the yaml. Example:

```yaml
functionality:
  name: test
  arguments:
    - name: "--input"
      type: "h5ad"
      required: true
      fields:
        obs: 
         - cluster
         - batch
         - `par.obsKey`
        uns: 
         - dataset_id
    - name: "--obsKey"
      type: string
      default: "cluster"
    - name: "--param"
      type: integer
      required: true
    - name: "--output"
      type: "h5ad"
      direction: "output"
      required: true
      fields:
        obs: [ cluster, batch ]
        obsm: [ dimred ]
        uns: [ dataset_id ]
```

## Option 3: Add validation script

You can specify custom resources to validate files / arguments.

```yaml
arguments:
  - name: "--input"
    type: "file"
    required: true
    validation_script: 
      type: python_script
      path: valid_input.py
      args: 
       ...
  - name: "--param"
    type: integer
    required: true
  - name: "--output"
    type: "file"
    direction: "output"
    required: true
    validation_script: 
      type: python_script
      path: valid_output.py
```

## Option 4: Template object

Allow passing a template object which contains all the required fields.

```yaml
arguments:
  - name: "--input"
    type: "file"
    required: true
    template: input.h5ad
  - name: "--param"
    type: integer
    required: true
  - name: "--output"
    type: "file"
    direction: "output"
    required: true
    template: output.h5ad
```

# Reusable h5ad checker with NXF DSL3

```groovy
channel
  | h5ad_checker(args = [ obs: ['cluster', 'batch'], uns: ['dataset_id'] ] )
  | method1
  | h5ad_checker(args = [ obs: ['cluster', 'batch'], obsm: [ 'X_pca' ], uns: ['dataset_id'] ] )
  | method2
```
