### ISSUE TITLE
Allow a string where a list of strings is expected in the config file

### ISSUE THREAD

**Issue by BlackDragonBE** [viash-io/viash#97]
### Current behaviour
Right now, when using a string where a list of strings is expected, you get a non-descriptive error.  
For example, let's say you want to expose port `8443` with the Docker platform and forgot that the `port` attribute is a list. Here's a snippet of what that might look like:

```yaml
platforms:
- type: docker
  image: ubuntu:focal
  port: "8443:8443"
```

Trying to run a component with the config in this state will result in this error:

```bash
Exception in thread "main" DecodingFailure(C[A], List(DownField(port), DownArray, DownField(platforms)))
```

To correct the mistake and get the container to run, you need to make `port` a list of strings, like so:

```yaml
platforms:
- type: docker
  image: ubuntu:focal
  port: [ "8443:8443" ]
```

This applies to all attributes where Viash expects a list.

### Wanted behaviour
Viash should allow a single string in place of a list of strings. The two examples above should be handled the same, like a list of strings with a single item.
