### ISSUE TITLE
Support automatic docker authentication inside executables 

### ISSUE THREAD

**Issue by dburkhardt** [viash-io/viash#99]
Currently, if a component relies on an image hosted on a private registry, like AWS ECR, the user must authenticate Docker so the image can be pulled locally.

The authentication command looks like: 

```
aws ecr get-login-password --region <region> | docker login --username AWS --password-stdin <account_id>.dkr.ecr.<region>.amazonaws.com
```

In my workflow, I specify the default region and account_id in my `bin/init` file in my components repository on GitHub. As those defaults are already specified, it would be great if a command like the above would be run automatically when I run a `viash` compiled executable.

Some caveats I can think of:
* Not all components in a repository will use the same registry defined in `bin/init` (although they currently are for our use case)
* Different image registries will have different authentication patterns
* The above command is compatible with AWS CLI v2, but not v1, which uses `aws ecr get-login`
* A user might not have the correct credentials configured in their environment when they run this command (perhaps due to having multiple AWS profiles)

**Comment by rcannood** [comment]
I was considering adding something to the `bin/init` that would allow you to specify how you'd want to log in by overriding a parameter in your viash components. However, this approach wouldn't work if you build the components in your repository (e.g. for a release) and give them someone else.

Since Docker has it's own system for storing credentials, wouldn't the following be a viable approach:

`bin/init` specifies the registry:
```bash
curl -fsSL get.viash.io | bash -s -- \
  --tag 0.5.9 \
  --viash bin/viash \
  --registry <account_id>.dkr.ecr.<region>.amazonaws.com
```

A separate viash component `src/login/config.vsh.yaml` allows you to log into the registry:
```yaml
functionality:
  name: login
  arguments:
    - type: string
      name: "--region"
      default: us-west
    - type: string
      name: "--user"
      default: AWS
    - type: string
      name: "--account_id"
      default: ...
    - type: string
      name: "--profile"
      default: default
  resources:
    - type: bash_script
      dest: script.sh
      text: "aws ecr get-login-password --region $par_region --profile $par_profile | docker login --username $par_user --password-stdin $par_account_id.dkr.ecr.$par_region.amazonaws.com"
platforms:
  - type: native
```

Since Docker stores the credentials locally, users would only have to run it once.

What do you think?

**Comment by dburkhardt** [comment]
I like this idea! I think the config solution is nice. Is the idea we would put the account ID and other information in the defaults for the `arguments`?

**Comment by rcannood** [comment]
Exactly! That way you can reuse the same component for multiple accounts. 

You can even make multiple builds of the same component by overriding the default values, e.g.:
```bash
viash build src/login/config.vsh.yaml -c '.functionality.arguments[.name == "--account_id"].default := "123123123"'
```

Regarding aws-cli v1 vs v2, I adapted the initial component a little so that it should work with both. What do you think?

```yaml
functionality:
  name: login
  description: To log in to an Amazon ECR registry
  arguments:
    - type: string
      name: "--region"
      default: us-west
      description: The region to use.
    - type: string
      name: "--account_id"
      default: "123456789123"
      description: The account alias or account ID for the AWS account.
    - type: string
      name: "--profile"
      default: default
      description: Use a specific profile from your credential file.
  resources:
    - type: bash_script
      dest: script.sh
      text: |
        # check whether necessary commands are available
        command -v aws >/dev/null 2>&1 || { echo >&2 "aws-cli needs to be installed. Aborting."; exit 1; }
        command -v sed >/dev/null 2>&1 || { echo >&2 "sed needs to be installed. Aborting."; exit 1; }
        
        # fetch password from aws
        if [[ `/usr/bin/aws --version` =~ "aws-cli/1" ]]; then
          # aws-cli v1
          AWSPASSWD=`/usr/bin/aws ecr get-login --profile $par_profile --registry-ids $par_account_id | sed 's#.*-p \([^ ]*\).*#\1#'`
        else
          # aws-cli v2
          AWSPASSWD=`aws ecr get-login-password \
            --region $par_region \
            --profile $par_profile`
        fi
        
        # print command and run
        echo '+ echo $AWSPASSWD |' "docker login --username AWS --password-stdin $par_account_id.dkr.ecr.$par_region.amazonaws.com"
        echo $AWSPASSWD | \
          docker login \
          --username AWS \
          --password-stdin $par_account_id.dkr.ecr.$par_region.amazonaws.com
platforms:
  - type: native
```
